volumes:

  catkin_workspace:

  shared_data:

  uav_custom_files:

  bag_files:

  logs:

services:
  # will copy session-specific data shared between containers from the shared_data container to a shared volume
  copy_catkin_workspace:
    image: uvdar_workspace:1.0.1
    volumes:
      - catkin_workspace:/tmp/docker/catkin_workspace_1:consistent
    tty: true
    command: sh -c "rm -rvf /tmp/docker/catkin_workspace_1/*; mkdir -pv /tmp/docker/catkin_workspace_1; cp -rv /etc/docker/catkin_workspace_1/* /tmp/docker/catkin_workspace_1/"

  copy_shared_data:
    image: shared_data:worlds
    volumes:
      - shared_data:/tmp/docker/shared_data:consistent
    tty: true
    command: sh -c "rm -rvf /tmp/docker/shared_data/*; mkdir -pv /tmp/docker/shared_data; cp -rv /etc/docker/shared_data/* /tmp/docker/shared_data/"

  # will copy uav-specific configs, launch files and other files from the uav-specific docker image to a shared volume
  copy_uav_custom_files:
    # image: fly4future/uav_custom_files
    image: uav_custom_files:uvdar
    volumes:
      - uav_custom_files:/tmp/docker/uav_custom_files:consistent
    tty: true
    command: sh -c "rm -rvf /tmp/docker/uav_custom_files/*; mkdir -pv /tmp/docker/uav_custom_files; cp -rv /etc/docker/uav_custom_files/${UAV_TYPE}/${UAV_ID}/* /tmp/docker/uav_custom_files/"

  # starts roscore
  # this is the first container in the ROS pipeline
  roscore:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    depends_on:
      - copy_shared_data
      - copy_uav_custom_files
    env_file:
      - ./stack.env
    tty: true
    command: roscore

# set sim time TRUE for bag playback
  rostime:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    depends_on:
      - roscore
    env_file:
      - ./stack.env
    tty: true
    command: bash -c "waitForRos && rosparam set use_sim_time false"

  # plays the rosbag for rerun
  bagfile:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    depends_on:
      - rostime
    env_file:
      - ./stack.env
    volumes:
      # Option A: bind mount your bag folder from the host
      - /home/mrs/bags/reflection:/etc/docker/bags/reflection:ro
    tty: true
    command: bash -c "waitForTime && sleep 1 && rosbag play /etc/docker/bags/reflection/1_2026_03_13_11_27_58/_2026-03-13-11-32-48.bag --clock"

  # starts the Reflection Node in rerun mode
  reflection_rerun:
    image: timlakemann/mrs_system_custom_python_pkg:0.0
    network_mode: host
    depends_on:
      - rostime
      - copy_catkin_workspace
    volumes:
      - catkin_workspace:/etc/docker/catkin_workspace_1:consistent
    env_file:
      - ./stack.env
    tty: true
    command: bash -c "waitForTime && sleep 1 && source /etc/docker/catkin_workspace_1/devel/setup.bash && roslaunch reflection_node reflection_rerun.launch"
  terminal:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    depends_on:
      - rostime
    env_file:
      - ./stack.env
    entrypoint: ["/bin/bash", "-c"]
    volumes:
      - bag_files:/etc/docker/bag_files:consistent
      - shared_data:/etc/docker/shared_data:consistent
      - uav_custom_files:/etc/docker/uav_custom_files:consistent
      - /dev/:/dev/
    command:
      - bash --rcfile /opt/ros/noetic/setup.bash
    privileged: true
    stdin_open: true
    tty: true

  # records timing topics
  record_timing:
    image: ctumrs/mrs_uav_system:${MRS_UAV_SYSTEM_VERSION}
    network_mode: host
    depends_on:
      - rostime
    volumes:
      - /home/mrs/bags/reflection/timing_only:/etc/docker/bags/timing_only:consistent
    env_file:
      - ./stack.env
    tty: true
    stop_grace_period: 10s
    command: bash -c "waitForTime && rosbag record -e '(.*)/reflection_localizer/timing(.*)' -O /etc/docker/bags/timing_only/robofly.bag"
